const Brand = [
  { value: 'Nike', label: 'Nike' },
  { value: 'Adidas', label: 'Adidas' },
  { value: 'Zara', label: 'Zara' },
  { value: 'H&M', label: 'H&M' },
  { value: 'Uniqlo', label: 'Uniqlo' },
  { value: 'Levi\'s', label: 'Levi\'s' },
  { value: 'Gucci', label: 'Gucci' },
  { value: 'Prada', label: 'Prada' },
  { value: 'Chanel', label: 'Chanel' },
  { value: 'Louis Vuitton', label: 'Louis Vuitton' },
  { value: 'Burberry', label: 'Burberry' },
  { value: 'Tommy Hilfiger', label: 'Tommy Hilfiger' },
  { value: 'Lacoste', label: 'Lacoste' },
  { value: 'Gap', label: 'Gap' },
  { value: 'Diesel', label: 'Diesel' },
  { value: 'Calvin Klein', label: 'Calvin Klein' },
  { value: 'Versace', label: 'Versace' },
  { value: 'Armani', label: 'Armani' },
  { value: 'Balenciaga', label: 'Balenciaga' },
  { value: 'Fendi', label: 'Fendi' },
  { value: 'Ralph Lauren', label: 'Ralph Lauren' },
  { value: 'Dolce & Gabbana', label: 'Dolce & Gabbana' },
  { value: 'BOSS', label: 'BOSS' },
  { value: 'Supreme', label: 'Supreme' },
  { value: 'Off-White', label: 'Off-White' },
  { value: 'Vans', label: 'Vans' },
  { value: 'Puma', label: 'Puma' },
  { value: 'Reebok', label: 'Reebok' },
  { value: 'Under Armour', label: 'Under Armour' },
  { value: 'Hermès', label: 'Hermès' },
  { value: 'Patagonia', label: 'Patagonia' },
  { value: 'Columbia', label: 'Columbia' },
  { value: 'North Face', label: 'North Face' },
  { value: 'Kenzo', label: 'Kenzo' },
  { value: 'Champion', label: 'Champion' },
  { value: 'Guess', label: 'Guess' },
  { value: 'Forever 21', label: 'Forever 21' },
  { value: 'Topshop', label: 'Topshop' },
  { value: 'Banana Republic', label: 'Banana Republic' },
  { value: 'Victoria\'s Secret', label: 'Victoria\'s Secret' },
  { value: 'ASOS', label: 'ASOS' },
  { value: 'Ted Baker', label: 'Ted Baker' },
  { value: 'Moncler', label: 'Moncler' },
  { value: 'Giorgio Armani', label: 'Giorgio Armani' },
  { value: 'Lululemon', label: 'Lululemon' },
  { value: 'Michael Kors', label: 'Michael Kors' },
  { value: 'Stone Island', label: 'Stone Island' },
  { value: 'Balmain', label: 'Balmain' },
  { value: 'Moschino', label: 'Moschino' },
  { value: 'Diesel', label: 'Diesel' },
  { value: "U.S. Polo Assn.", label: "U.S. Polo Assn."},
  { value: "Jack & Jones", label: "Jack & Jones"},
  { value: "Roadster", label: "Roadster"},
  { value: "Park Avenue", label: "Park Avenue"},
  { value: "Pepe Jeans", label: "Pepe Jeans"},
  { value: "Mast & Harbour", label: "Mast & Harbour"},
  { value: "Van Heusen", label: "Van Heusen"},
]

export default Brand

